from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from utils.code_retriever import read_context
from utils.git_utils import extract_modified_files, looks_like_unified_diff


class PatchGenerator:
    """Generate or accept a unified diff patch for the localized bug."""

    def __init__(self, *, llm_client: Any | None = None, prompt_path: str | Path | None = None) -> None:
        self.llm_client = llm_client
        self.prompt_path = Path(prompt_path) if prompt_path else None

    def generate(self, ticket_json: dict[str, Any], bug_location: dict[str, Any], repo_path: str) -> dict[str, Any]:
        provided_patch = _first_patch(ticket_json)
        if provided_patch:
            return self._patch_result(
                provided_patch,
                explanation="Patch was provided by the input ticket.",
                bug_location=bug_location,
            )

        confidence = _confidence_policy(bug_location)
        if not confidence["recommend_patch_generation"]:
            return self._manual_patch_guidance(
                bug_location,
                explanation=(
                    "Localization confidence is not high enough for automatic patch generation. "
                    "Use the Top-k context as review guidance before writing a patch."
                ),
                blocked_by_confidence=True,
            )

        if self.llm_client is not None:
            prompt = self._build_prompt(ticket_json, bug_location, repo_path)
            generated = self.llm_client.generate(prompt)
            if looks_like_unified_diff(generated):
                return self._patch_result(
                    generated,
                    explanation="Patch generated by configured LLM client.",
                    bug_location=bug_location,
                )

        return self._manual_patch_guidance(
            bug_location,
            explanation=(
                "No unified diff was provided and no patch-generation model is configured. "
                "Top-k localization context is attached for a manual patch suggestion."
            ),
            blocked_by_confidence=False,
        )

    def _patch_result(self, patch_text: str, *, explanation: str, bug_location: dict[str, Any] | None = None) -> dict[str, Any]:
        confidence = _confidence_policy(bug_location or {})
        location = bug_location.get("bug_location", {}) if isinstance(bug_location, dict) else {}
        localization_context = _localization_context(bug_location or {})
        modified_files = extract_modified_files(patch_text)
        return {
            "patch_status": "provided" if explanation.startswith("Patch was provided") else "generated",
            "patch": patch_text,
            "modified_files": modified_files,
            "explanation": explanation,
            "requires_manual_patch": False,
            "requires_manual_review": bool(confidence["should_manual_review"]),
            "confidence_level": confidence["confidence_level"],
            "recommend_patch_generation": confidence["recommend_patch_generation"],
            "bug_location": location,
            "localization_context": localization_context,
        }

    def _manual_patch_guidance(
        self,
        bug_location: dict[str, Any],
        *,
        explanation: str,
        blocked_by_confidence: bool,
    ) -> dict[str, Any]:
        location = bug_location.get("bug_location", {}) if isinstance(bug_location, dict) else {}
        confidence = _confidence_policy(bug_location)
        localization_context = _localization_context(bug_location)
        file_path = str(location.get("file") or "")
        patch_status = (
            "blocked_low_confidence"
            if confidence["confidence_level"] == "low"
            else "needs_review_before_patch"
            if blocked_by_confidence
            else "suggestion_only"
        )
        return {
            "patch_status": patch_status,
            "patch": "",
            "modified_files": [file_path] if file_path and not blocked_by_confidence else [],
            "explanation": explanation,
            "requires_manual_patch": True,
            "requires_manual_review": True if blocked_by_confidence else bool(confidence["should_manual_review"]),
            "confidence_level": confidence["confidence_level"],
            "recommend_patch_generation": confidence["recommend_patch_generation"],
            "bug_location": location,
            "localization_context": localization_context,
            "patch_suggestion": {
                "type": "manual_patch_guidance",
                "target_file": file_path,
                "target_symbol": location.get("function", ""),
                "confidence_level": confidence["confidence_level"],
                "uncertainty_reason": confidence["uncertainty_reason"],
                "suggested_action": (
                    "Inspect the top-ranked suspicious file and create a minimal unified diff after review."
                    if confidence["recommend_patch_generation"]
                    else "Review the Top-k candidates before deciding whether a patch should be generated."
                ),
            },
        }

    def _build_prompt(self, ticket_json: dict[str, Any], bug_location: dict[str, Any], repo_path: str) -> str:
        template = ""
        if self.prompt_path and self.prompt_path.exists():
            template = self.prompt_path.read_text(encoding="utf-8")
        location = bug_location.get("bug_location", {}) if isinstance(bug_location, dict) else {}
        localization_context = _localization_context(bug_location)
        context = ""
        if location.get("file"):
            try:
                context = read_context(repo_path, location["file"], int(location.get("line_start", 1)), int(location.get("line_end", 1)))
            except Exception:
                context = ""
        if not template:
            template = (
                "Generate a safe unified diff patch for the bug ticket and localized code. "
                "Use the Top-k localization context as guidance, but modify only the minimal necessary file(s). "
                "Return only a unified diff.\n\nTicket:\n{ticket_json}\n\nLocation:\n{bug_location}\n\n"
                "Localization context:\n{localization_context}\n\nCode:\n{context}"
            )
        return template.format(
            ticket_json=ticket_json,
            bug_location=bug_location,
            localization_context=json.dumps(localization_context, ensure_ascii=False, indent=2),
            context=context,
        )


def _first_patch(ticket_json: dict[str, Any]) -> str:
    for key in ("patch", "proposed_patch", "suggested_patch", "unified_diff"):
        value = ticket_json.get(key)
        if isinstance(value, str) and value.strip():
            return value if value.endswith("\n") else value + "\n"
    return ""


def _confidence_policy(bug_location: dict[str, Any]) -> dict[str, Any]:
    location = bug_location.get("bug_location", {}) if isinstance(bug_location, dict) else {}
    level_value = bug_location.get("confidence_level") or location.get("confidence_level")
    manual_value = bug_location.get("should_manual_review", location.get("should_manual_review"))
    recommend_value = bug_location.get("recommend_patch_generation", location.get("recommend_patch_generation"))
    if level_value is None and manual_value is None and recommend_value is None:
        return {
            "confidence_level": "low",
            "uncertainty_reason": "Localization confidence metadata is missing; manual review is required before patch generation.",
            "should_manual_review": True,
            "recommend_patch_generation": False,
        }

    level = str(level_value or "low")
    should_manual_review = bool(manual_value if manual_value is not None else level != "high")
    recommend_patch_generation = bool(recommend_value if recommend_value is not None else level == "high" and not should_manual_review)
    return {
        "confidence_level": level,
        "uncertainty_reason": str(bug_location.get("uncertainty_reason") or location.get("uncertainty_reason") or ""),
        "should_manual_review": should_manual_review,
        "recommend_patch_generation": recommend_patch_generation,
    }


def _localization_context(bug_location: dict[str, Any], *, limit: int = 5) -> list[dict[str, Any]]:
    candidates = bug_location.get("localized_candidates") if isinstance(bug_location, dict) else None
    if not isinstance(candidates, list):
        candidates = bug_location.get("localized_files") if isinstance(bug_location, dict) else None
    if not isinstance(candidates, list):
        candidates = bug_location.get("candidates") if isinstance(bug_location, dict) else None
    if not isinstance(candidates, list):
        return []

    confidence = _confidence_policy(bug_location)
    rows: list[dict[str, Any]] = []
    for index, candidate in enumerate(candidates[:limit], start=1):
        if not isinstance(candidate, dict):
            continue
        repository_context = candidate.get("repository_context") if isinstance(candidate.get("repository_context"), dict) else {}
        rows.append(
            {
                "rank": candidate.get("rank", index),
                "file_path": candidate.get("file_path") or candidate.get("file") or "",
                "function_name": candidate.get("function_name") or candidate.get("function") or candidate.get("best_function_name") or "",
                "score": candidate.get("score") or candidate.get("final_score"),
                "reason": candidate.get("reason", ""),
                "confidence_level": confidence["confidence_level"],
                "should_manual_review": confidence["should_manual_review"],
                "recommend_patch_generation": confidence["recommend_patch_generation"],
                "repository_context": _compact_repository_context(repository_context),
            }
        )
    return rows


def _compact_repository_context(context: dict[str, Any]) -> dict[str, Any]:
    if not context:
        return {}
    return {
        "context_strategy": context.get("context_strategy", ""),
        "file_path": context.get("file_path", ""),
        "primary_symbol": context.get("primary_symbol", ""),
        "primary_line_range": context.get("primary_line_range", []),
        "imports": list(context.get("imports") or [])[:4],
        "related_files": [
            {
                "file_path": row.get("file_path", ""),
                "relationship": row.get("relationship", ""),
            }
            for row in list(context.get("related_files") or [])[:3]
            if isinstance(row, dict)
        ],
        "symbol_references": [
            {
                "file_path": row.get("file_path", ""),
                "symbol": row.get("symbol", ""),
            }
            for row in list(context.get("symbol_references") or [])[:3]
            if isinstance(row, dict)
        ],
    }
