from __future__ import annotations

import json
import re
from pathlib import Path
from typing import Any

from utils.code_retriever import read_context
from utils.git_utils import extract_modified_files, looks_like_unified_diff
from utils.patch_context import PatchContextError, build_stage3_context


class PatchGenerator:
    """Generate or accept a unified diff patch for the localized bug."""

    def __init__(self, *, llm_client: Any | None = None, prompt_path: str | Path | None = None) -> None:
        self.llm_client = llm_client
        self.prompt_path = Path(prompt_path) if prompt_path else None

    def generate(self, ticket_json: dict[str, Any], bug_location: dict[str, Any], repo_path: str) -> dict[str, Any]:
        provided_patch = _first_patch(ticket_json)
        if provided_patch:
            return self._patch_result(
                provided_patch,
                explanation="Patch was provided by the input ticket.",
                bug_location=bug_location,
            )

        confidence = _confidence_policy(bug_location)
        if not confidence["recommend_patch_generation"]:
            return self._manual_patch_guidance(
                bug_location,
                explanation=(
                    "Localization confidence is not high enough for automatic patch generation. "
                    "Use the Top-k context as review guidance before writing a patch."
                ),
                blocked_by_confidence=True,
            )

        if self.llm_client is not None:
            try:
                prompt = self._build_prompt(ticket_json, bug_location, repo_path)
            except (PatchContextError, OSError) as exc:
                result = self._manual_patch_guidance(
                    bug_location, explanation=str(exc), blocked_by_confidence=True,
                )
                result.update(patch_status="blocked_invalid_context", recommend_patch_generation=False,
                              requires_manual_review=True, modified_files=[])
                return result
            generated = self.llm_client.generate(prompt)
            normalized = _extract_generated_diff(generated)
            if (normalized and _has_effective_change(normalized)
                    and _patch_targets_localized_files(normalized, bug_location)):
                return self._patch_result(
                    normalized,
                    explanation="Patch generated by configured LLM client.",
                    bug_location=bug_location,
                )

            result = self._manual_patch_guidance(
                bug_location,
                explanation=(
                    "The patch model response was not one valid unified diff limited to the "
                    "localized source files. Review or regenerate the patch."
                ),
                blocked_by_confidence=False,
            )
            result.update(patch_status="blocked_invalid_generated_patch", modified_files=[])
            return result

        return self._manual_patch_guidance(
            bug_location,
            explanation=(
                "No unified diff was provided and no patch-generation model is configured. "
                "Top-k localization context is attached for a manual patch suggestion."
            ),
            blocked_by_confidence=False,
        )

    def _patch_result(self, patch_text: str, *, explanation: str, bug_location: dict[str, Any] | None = None) -> dict[str, Any]:
        confidence = _confidence_policy(bug_location or {})
        location = _primary_location(bug_location or {})
        localization_context = _localization_context(bug_location or {})
        modified_files = extract_modified_files(patch_text)
        return {
            "patch_status": "provided" if explanation.startswith("Patch was provided") else "generated",
            "patch": patch_text,
            "modified_files": modified_files,
            "explanation": explanation,
            "requires_manual_patch": False,
            "requires_manual_review": bool(confidence["should_manual_review"]),
            "confidence_level": confidence["confidence_level"],
            "recommend_patch_generation": confidence["recommend_patch_generation"],
            "bug_location": location,
            "localization_context": localization_context,
        }

    def _manual_patch_guidance(
        self,
        bug_location: dict[str, Any],
        *,
        explanation: str,
        blocked_by_confidence: bool,
    ) -> dict[str, Any]:
        location = _primary_location(bug_location)
        confidence = _confidence_policy(bug_location)
        localization_context = _localization_context(bug_location)
        file_path = str(location.get("file") or "")
        patch_status = (
            "blocked_low_confidence"
            if confidence["confidence_level"] == "low"
            else "needs_review_before_patch"
            if blocked_by_confidence
            else "suggestion_only"
        )
        return {
            "patch_status": patch_status,
            "patch": "",
            "modified_files": [file_path] if file_path and not blocked_by_confidence else [],
            "explanation": explanation,
            "requires_manual_patch": True,
            "requires_manual_review": True if blocked_by_confidence else bool(confidence["should_manual_review"]),
            "confidence_level": confidence["confidence_level"],
            "recommend_patch_generation": confidence["recommend_patch_generation"],
            "bug_location": location,
            "localization_context": localization_context,
            "patch_suggestion": {
                "type": "manual_patch_guidance",
                "target_file": file_path,
                "target_symbol": location.get("function", ""),
                "confidence_level": confidence["confidence_level"],
                "uncertainty_reason": confidence["uncertainty_reason"],
                "suggested_action": (
                    "Inspect the top-ranked suspicious file and create a minimal unified diff after review."
                    if confidence["recommend_patch_generation"]
                    else "Review the Top-k candidates before deciding whether a patch should be generated."
                ),
            },
        }

    def _build_prompt(self, ticket_json: dict[str, Any], bug_location: dict[str, Any], repo_path: str) -> str:
        template = ""
        if self.prompt_path and self.prompt_path.exists():
            template = self.prompt_path.read_text(encoding="utf-8")
        location = _primary_location(bug_location)
        localization_context = _localization_context(bug_location)
        context = ""
        stage3 = _stage3_requested(bug_location)
        if stage3:
            source_location = dict(bug_location)
            ticket_base = str(ticket_json.get("base_commit") or "")
            if ticket_base and source_location.get("base_commit") and ticket_base != source_location["base_commit"]:
                raise PatchContextError("Ticket and localization base_commit disagree.")
            if ticket_base:
                source_location.setdefault("base_commit", ticket_base)
            context = json.dumps(build_stage3_context(source_location, repo_path), ensure_ascii=False, indent=2)
        elif location.get("file"):
            try:
                context = read_context(repo_path, location["file"], int(location.get("line_start", 1)), int(location.get("line_end", 1)))
            except Exception:
                context = ""
        if not template:
            template = (
                "Generate a safe unified diff patch for the bug ticket and localized code. "
                "Use the Top-k localization context as guidance, but modify only the minimal necessary file(s). "
                "Return only a unified diff.\n\nTicket:\n{ticket_json}\n\nLocation:\n{bug_location}\n\n"
                "Localization context:\n{localization_context}\n\nCode:\n{context}"
            )
        if stage3 and "{context}" not in template:
            template += "\n\nComplete source context:\n{context}"
        return template.format(
            ticket_json=_public_ticket(ticket_json),
            bug_location=location,
            localization_context=json.dumps(localization_context, ensure_ascii=False, indent=2),
            context=context,
        )


def _first_patch(ticket_json: dict[str, Any]) -> str:
    # Benchmark developer patches are evaluator evidence, never generated output.
    if ticket_json.get("source_dataset") or ticket_json.get("instance_id"):
        return ""
    for key in ("patch", "proposed_patch", "suggested_patch", "unified_diff"):
        value = ticket_json.get(key)
        if isinstance(value, str) and value.strip():
            return value if value.endswith("\n") else value + "\n"
    return ""


def _extract_generated_diff(response: str) -> str:
    """Return one clean unified diff from a plain or Markdown-fenced response."""
    text = (response or "").strip()
    if not text:
        return ""
    fenced = re.findall(r"```(?:diff|patch)?\s*\r?\n(.*?)```", text, flags=re.IGNORECASE | re.DOTALL)
    candidates = [block.strip() for block in fenced if looks_like_unified_diff(block)]
    if len(candidates) == 1:
        candidate = _repair_hunk_counts(candidates[0] + "\n")
        return candidate if _has_only_diff_lines(candidate) else ""
    first = next((index for index, line in enumerate(text.splitlines())
                  if line.startswith(("diff --git ", "--- a/", "--- /dev/null"))), None)
    if first is None:
        return ""
    lines = text.splitlines()
    if any(line.strip() for line in lines[:first]):
        return ""
    candidate = "\n".join(lines[first:]).strip() + "\n"
    if not looks_like_unified_diff(candidate):
        return ""
    candidate = _repair_hunk_counts(candidate)
    return candidate if _has_only_diff_lines(candidate) else ""


def _repair_hunk_counts(patch_text: str) -> str:
    """Correct model-generated unified-diff hunk counts from the hunk body."""
    lines = patch_text.rstrip("\n").splitlines()
    header = re.compile(r"^@@ -(\d+)(?:,(\d+))? \+(\d+)(?:,(\d+))? @@(.*)$")
    index = 0
    while index < len(lines):
        match = header.match(lines[index])
        if not match:
            index += 1
            continue
        end = index + 1
        old_count = new_count = 0
        while end < len(lines) and not lines[end].startswith(("@@ ", "diff --git ", "--- a/", "--- /dev/null")):
            if lines[end].startswith("\\ No newline at end of file"):
                end += 1
                continue
            if lines[end].startswith((" ", "-")):
                old_count += 1
            if lines[end].startswith((" ", "+")):
                new_count += 1
            end += 1
        old_start, new_start, suffix = match.group(1), match.group(3), match.group(5)
        old_range = old_start if old_count == 1 else f"{old_start},{old_count}"
        new_range = new_start if new_count == 1 else f"{new_start},{new_count}"
        lines[index] = f"@@ -{old_range} +{new_range} @@{suffix}"
        index = end
    return "\n".join(lines) + "\n"


def _has_only_diff_lines(patch_text: str) -> bool:
    in_hunk = False
    for line in patch_text.rstrip("\n").splitlines():
        if line.startswith("diff --git "):
            in_hunk = False
        elif line.startswith("@@ "):
            in_hunk = True
        elif in_hunk and not line.startswith((" ", "+", "-", "\\ No newline at end of file")):
            return False
    return True


def _has_effective_change(patch_text: str) -> bool:
    removed = [line[1:] for line in patch_text.splitlines()
               if line.startswith("-") and not line.startswith("--- ")]
    added = [line[1:] for line in patch_text.splitlines()
             if line.startswith("+") and not line.startswith("+++ ")]
    return bool(removed or added) and removed != added


def _patch_targets_localized_files(patch_text: str, bug_location: dict[str, Any]) -> bool:
    modified = extract_modified_files(patch_text)
    if not modified or any(_is_test_path(path) for path in modified):
        return False
    if _stage3_requested(bug_location):
        rows = bug_location.get("stage3_ranked_symbols") or []
        allowed = {str(row.get("file_path") or "").replace("\\", "/")
                   for row in rows[:5] if isinstance(row, dict)}
    else:
        allowed = {str(_primary_location(bug_location).get("file") or "").replace("\\", "/")}
    return bool(allowed) and set(modified).issubset(allowed)


def _is_test_path(path: str) -> bool:
    normalized = "/" + path.replace("\\", "/").lower().strip("/")
    name = normalized.rsplit("/", 1)[-1]
    return "/test/" in normalized or "/tests/" in normalized or name.startswith("test_") or name.endswith("_test.py")


def _confidence_policy(bug_location: dict[str, Any]) -> dict[str, Any]:
    location = bug_location.get("bug_location", {}) if isinstance(bug_location, dict) else {}
    level_value = bug_location.get("confidence_level") or location.get("confidence_level")
    manual_value = bug_location.get("should_manual_review", location.get("should_manual_review"))
    recommend_value = bug_location.get("recommend_patch_generation", location.get("recommend_patch_generation"))
    if level_value is None and manual_value is None and recommend_value is None:
        return {
            "confidence_level": "low",
            "uncertainty_reason": "Localization confidence metadata is missing; manual review is required before patch generation.",
            "should_manual_review": True,
            "recommend_patch_generation": False,
        }

    level = str(level_value or "low")
    should_manual_review = bool(manual_value if manual_value is not None else level != "high")
    recommend_patch_generation = bool(recommend_value if recommend_value is not None else level == "high" and not should_manual_review)
    return {
        "confidence_level": level,
        "uncertainty_reason": str(bug_location.get("uncertainty_reason") or location.get("uncertainty_reason") or ""),
        "should_manual_review": should_manual_review,
        "recommend_patch_generation": recommend_patch_generation,
    }


def _localization_context(bug_location: dict[str, Any], *, limit: int = 5) -> list[dict[str, Any]]:
    candidates = (bug_location.get("stage3_ranked_symbols") if _stage3_requested(bug_location)
                  else bug_location.get("localized_candidates"))
    if _stage3_requested(bug_location) and not isinstance(candidates, list):
        return []
    if not isinstance(candidates, list):
        candidates = bug_location.get("localized_files") if isinstance(bug_location, dict) else None
    if not isinstance(candidates, list):
        candidates = bug_location.get("candidates") if isinstance(bug_location, dict) else None
    if not isinstance(candidates, list):
        return []

    confidence = _confidence_policy(bug_location)
    rows: list[dict[str, Any]] = []
    for index, candidate in enumerate(candidates[:limit], start=1):
        if not isinstance(candidate, dict):
            continue
        repository_context = candidate.get("repository_context") if isinstance(candidate.get("repository_context"), dict) else {}
        rows.append(
            {
                "rank": candidate.get("rank", index),
                "file_path": candidate.get("file_path") or candidate.get("file") or "",
                "function_name": candidate.get("symbol_qualified_name") or candidate.get("function_name") or candidate.get("function") or candidate.get("best_function_name") or "",
                "start_line": candidate.get("start_line", candidate.get("line_start")),
                "end_line": candidate.get("end_line", candidate.get("line_end")),
                "symbol_kind": candidate.get("symbol_kind", ""),
                "score": candidate.get("score", candidate.get("final_score")),
                "reason": candidate.get("reason", ""),
                "confidence_level": confidence["confidence_level"],
                "should_manual_review": confidence["should_manual_review"],
                "recommend_patch_generation": confidence["recommend_patch_generation"],
                "repository_context": _compact_repository_context(repository_context),
            }
        )
    return rows


def _stage3_requested(location: dict[str, Any]) -> bool:
    diagnostics = location.get("stage3_diagnostics") or {}
    return bool(location.get("stage3_ranked_symbols") or diagnostics.get("localization_requested")
                or ("stage3_ranked_symbols" in location and "localization_requested" not in diagnostics))


def _primary_location(location: dict[str, Any]) -> dict[str, Any]:
    if _stage3_requested(location):
        symbols = location.get("stage3_ranked_symbols") or []
        if not symbols or not isinstance(symbols[0], dict):
            return {}
        first = symbols[0]
        return {"file": first.get("file_path", ""), "function": first.get("symbol_qualified_name", ""),
                "line_start": first.get("start_line"), "line_end": first.get("end_line")}
    return location.get("bug_location", {})


def _public_ticket(ticket: dict[str, Any]) -> dict[str, Any]:
    keys = ("ticket_id", "id", "title", "description", "bug_report", "error_message",
            "stack_trace", "logs", "steps_to_reproduce", "expected_behavior", "actual_behavior",
            "product", "component", "version", "os", "repo", "base_commit")
    return {key: ticket[key] for key in keys if key in ticket and isinstance(ticket[key], (str, int, float, bool))}


def _compact_repository_context(context: dict[str, Any]) -> dict[str, Any]:
    if not context:
        return {}
    return {
        "context_strategy": context.get("context_strategy", ""),
        "file_path": context.get("file_path", ""),
        "primary_symbol": context.get("primary_symbol", ""),
        "primary_line_range": context.get("primary_line_range", []),
        "imports": list(context.get("imports") or [])[:4],
        "related_files": [
            {
                "file_path": row.get("file_path", ""),
                "relationship": row.get("relationship", ""),
            }
            for row in list(context.get("related_files") or [])[:3]
            if isinstance(row, dict)
        ],
        "symbol_references": [
            {
                "file_path": row.get("file_path", ""),
                "symbol": row.get("symbol", ""),
            }
            for row in list(context.get("symbol_references") or [])[:3]
            if isinstance(row, dict)
        ],
    }
